### ISSUE TITLE
Allow site users and administrators to edit content

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#11]
Options
----------

- Use Wagtail
- Use a MarkDown editor. Could use [SimpleMDE](https://simplemde.com/)

**Comment by alee** [comment]
https://groups.google.com/forum/#!topic/wagtail/Get0wrrJ-3c

https://www.caktusgroup.com/blog/2016/02/15/wagtail-2-steps-adding-pages-outside-cms/
