### ISSUE TITLE
bootstrap 4 offset classes not working in form

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#126]
According to https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid we should be able to use `offset-<size>-<1:12>` css classes in our forms to shift things over. However, this does not appear to work.

Look into updating bootstrap in frontend or possible scss overrides

**Comment by cpritcha** [comment]
Those classes don't exist in the Bootstrap 4 beta. See https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns
