### ISSUE TITLE
improve fs api

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#157]
several issues arising from migration:

1. log filetype mismatches as warning
2. ignore system directories
3. skip mimetype checking / validation on the code directory. eventually we'll want to run async processes on the uploaded files though
4. __MACOSX directories are still present in the sip. For an example, look for /codebases/5734 on the filesystem - please double check the fs filtering logic

**Comment by cpritcha** [comment]
5. don't do any mimetype checking for the data directory

**Comment by alee** [comment]
Are docx files not being considered valid docs files? For example https://sentry.commons.asu.edu/comses/core/issues/17568/ is showing `File type mismatch for file docs/nZEB_notes_updated.docx`
