### ISSUE TITLE
Decide what to do with OpenABM ModelVersion 'other' folders

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#168]
A handful (< 5) ModelVersions have other folders containing miscellaneous content. Right now we ignore that content.

**Comment by alee** [comment]
Let's generate a report of what's in these directories and we can discuss at our next meeting

**Comment by alee** [comment]
defunct now - one model author has already contacted us with updates based on missing content that was in the `other` directory that wasn't migrated over but we can handle these on a case-by-case basis from here on out
