### ISSUE TITLE
Add a contact link on the bottom of base template

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#181]
Need to know who to contact for any technical problems. Could be link to the GitHub issues page and the comses email.

**Comment by alee** [comment]
Good idea, how about adding a "Report a bug" link that sends an email to comses-dev google group or auto-creates a github issue might be useful. https://fire.fundersclub.com/ - linking to the github issues page forces people to create a github account which is OK but not ideal

**Comment by alee** [comment]
Something like `Terms of Service | Contact Us`
