### ISSUE TITLE
improve front page load time

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#184]
The blue banner needs to be optimized for web, it loads too slowly. 

May also need to optimize other parts of the page, check in DDT / new relic

**Comment by cpritcha** [comment]
Adding `image-webpack-loader` reduced blue banner from 403kb to 165kb ad27468db59b0bf3073ff7dc0d6392022bafa860

**Comment by alee** [comment]
@cpritcha can you take a quick look at the various list pages in django-debug-toolbar and create a report / rundown of where we should tune our queries?

**Comment by cpritcha** [comment]
sure. I'll take a look.

**Comment by alee** [comment]
closing for now, revisit later
