### ISSUE TITLE
codemeta not being generated on legacy import

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#206]
legacy file migration only generates 10 codemeta.json files - could be because `library.fs` is finding "problems" in the legacy codebases?

**Comment by alee** [comment]
also need to add logic to update codemeta based on the incoming data, only the initial codemeta.json file was being written out

**Comment by cpritcha** [comment]
Fixed by a9677a693aaa44f4f93bfef416e3d25b868baf44
