### ISSUE TITLE
user detail and list page improvements

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#218]
## list page 
- [x] don't show "become a member" to authenticated users
- [x] add sort by date joined, last name / first name (others?)
- [ ] improve layout (nebulous)

## detail page
- [x] add full member checkbox to edit page and some kind of full member badge to detail page
- [x] add help text for markdown text fields with links to formatting guidelines ala github
- [x] add group memberships (comses reviewers)

**Comment by cpritcha** [comment]
The simplemde component has a help button (question mark) that opens up a new page with their markdown guide

**Comment by alee** [comment]
That's fine, but we still need some text that either opens up the new page or directs users to click that button to learn more about the formatting style. Just something like the below `Styling with Markdown is supported` that GitHub does would be fine.

**Comment by cpritcha** [comment]
Added display of member reviewer group in aeb6c32be5578ae138cb01c10d715276504a2fac
