### ISSUE TITLE
'Connect your ORCID account' link broken

### ISSUE THREAD

**Issue by cmbarton** [comses/core.comses.net#219]
The link (on profile page) redirects to sandbox.orcid.org, with the message: 

Warning! sandbox.orcid.org is a test website. ORCID.org is the official website. Sandbox only sends email messages to mailinator.com email addresses, see Sandbox FAQ for more information
 ORCID logo
There has been a problem with the server. If this problem persists, please contact support.

**Comment by alee** [comment]
Thanks Michael, this is a known issue that we're tracking at #156 - we're waiting to get production credentials to access ORCID.
