### ISSUE TITLE
edit profile bugs

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#232]
- [x] adding degrees doesn't appear to save properly
- [x] institution should not be required
- [x] should not be able to change email to existing email
- [x] changing email should trigger another round of django-allauth email verification / validation #231 
- [ ] failed server-side validation just displays "Failed server-side validation"

**Comment by cpritcha** [comment]
Could you explain the problem with adding degrees? I don't see anything wrong.

**Comment by alee** [comment]
The degree field isn't saving any values

**Comment by alee** [comment]
Ah, I think this might require better documentation. You have to hit the "enter" key after entering something. I was tabbing out or just clicking "Save" after entering data. Regardless, clicking "Save" after entering data should save that data without an explicit return.

**Comment by alee** [comment]
failed server side validation still doesn't transfer properly, tracked on #251
