### ISSUE TITLE
Server side Markdown sanitization and rendering

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#26]
Options

- Use [django-markupfield](https://github.com/jamesturk/django-markupfield) and [bleach](https://bleach.readthedocs.io/en/latest/index.html)
- Subclass TextField and use [bleach](https://bleach.readthedocs.io/en/latest/index.html)

**Comment by cpritcha** [comment]
Could use [Vue2 Medium Editor](https://github.com/FranzSkuffka/vue-medium-editor) to edit the text and keep the text as html server-side instead of markdown.

**Comment by alee** [comment]
Nah, I'd rather not keep HTML server-side. Keep it as markdown server-side, just sanitize it on the way out.

**Comment by cpritcha** [comment]
Based on our conversation I'll make custom markdown field in django. Before saving the data in the database and retrieving data from the database some preprocessing will occur.

1. convert markdown to html (with markdown package)
2. sanitize html (with bleach)
3. convert html to markdown using [html2text](https://github.com/Alir3z4/html2text)

We can always cache the html results.
