### ISSUE TITLE
improve sort by for jobs and events

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#285]
Current sort by has options that are irrelevant for jobs and events. Should instead be:

Jobs:
- application deadline
- last modified
- relevance
- anything else?

Events:
- all deadlines (early registration, submission)
- start date
- last modified
- relevance
- anything else?

**Comment by cpritcha** [comment]
Fixed by fa8a80e96c8e91e627bf8b6de9cea9206c2cde6a
