### ISSUE TITLE
Add support for accessing code docstrings in Sphinx for readthedocs

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#313]
ReadTheDocs (the service) doesn't support building the docs with a custom Docker image.  Possible solution: make one settings configuration that works outside of Docker.

**Comment by alee** [comment]
Can we create a service definition to build readthedocs in dc-dev.yml or dc-prod.yml? Ideally we'll deploy docs in our .travis.yml on a successful build.

**Comment by cpritcha** [comment]
That would be better. I'll see if I can find another project that does that.

**Comment by alee** [comment]
https://github.com/rtfd/readthedocs-docker-images

**Comment by cpritcha** [comment]
comses.github.io/core.comses.net has a github pages build that will works with our docker build

**Comment by cpritcha** [comment]
Decided to use gh-pages
