### ISSUE TITLE
Create IP whitelist for staging site

### ISSUE THREAD

**Issue by cpritcha** [comses/core.comses.net#320]
```
tcp-request session accept if { src -f /etc/haproxy/whitelist.lst }
```

should work. Look at the [docs](http://cbonte.github.io/haproxy-dconv/1.9/configuration.html) and search for whitelist more information.

**Comment by alee** [comment]
https://raymii.org/s/snippets/haproxy_restrict_specific_urls_to_specific_ip_addresses.html
