### ISSUE TITLE
all Journal descriptions turned to `foo`

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#323]
@cpritcha have any idea why this may have occurred?

**Comment by cpritcha** [comment]
I'll take a look.

**Comment by cpritcha** [comment]
The default value in the migration 0003_add_markdown_field_to_journal_description.py for the rendered description is foo. I'll see if adding a migration to change the default value fixes it.

**Comment by cpritcha** [comment]
Easiest Fix - force rerender all the rendered journal html

```python
for j in Journal.objects.iterator():
   j.description = j.description.raw
   j.save()
```
