### ISSUE TITLE
import forum + comments into discourse

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#37]
Need to sync users between Discourse + Wagtail first.

Forum.json + Comments.json

Comments.json also has comments attached to other nodes (including replies to Forum posts in Forum.json), which we may want to import to discourse as well.

**Comment by alee** [comment]
See also 

- Users API post endpoint http://docs.discourse.org/#tag/Users%2Fpaths%2F~1users%2Fpost
- https://meta.discourse.org/t/custom-user-fields-for-plugins/14956

**Comment by cpritcha** [comment]
Explore using [SSO](https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045) (particularly `/admin/users/sync_sso` and `/users/by-external/:id.json`) to manage accounts.

**Comment by alee** [comment]
SSO is now functional on forum.comses.net and test.comses.net if you'd like to test that out.

There's also import scripts that run directly off Drupal that would be good to at least read (creating taxonomy, etc.)

https://github.com/discourse/discourse/tree/master/script/import_scripts
