### ISSUE TITLE
set up production webpack deploy

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#52]
`npm run build` is currently failing - we need to fix this for prod deployment.

https://vuejs.org/v2/guide/deployment.html

**Comment by cpritcha** [comment]
Could use [Multi-Stage Dockerfile](https://ordina-jworks.github.io/conference/2017/04/18/DockerCon-Multi-Stage-Builds-And-More.html) when it is released.

**Comment by alee** [comment]
Look carefully at

https://github.com/Microsoft/TypeScript-Vue-Starter

and compare with our webpack / typescript / vuejs config.

**Comment by alee** [comment]
Also follow guidelines from https://vuejs.org/v2/guide/typescript.html
