### ISSUE TITLE
refactor create_or_edit_routes

### ISSUE THREAD

**Issue by alee** [comses/core.comses.net#70]
all /create routes are broken right now for some reason

**Comment by alee** [comment]
this was caused by incorrect ordering, create_or_update_edit_routes has to be first in line, otherwise the standard ModelViewSet + SimpleRouter tries to soak up `/<model-name>/<anything>` to look up the detail view.

we should override [SimpleRouter](http://www.django-rest-framework.org/api-guide/routers/#simplerouter) or find another way around this problem, eventually

**Comment by cpritcha** [comment]
`lookup_value_regex` is responsible for changing the regex on matched on a viewset.
